language: php

sudo: false

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
    - SYMFONY_VERSION=2.7.* # LTS
    - SYMFONY_VERSION=2.8.* # LTS
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=3.3.*
    - SYMFONY_VERSION=3.4.* # LTS
    - SYMFONY_VERSION=4.0.*

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install:
    - composer update

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit --coverage-text

after_success:
    - travis_retry php vendor/bin/coveralls

matrix:
    exclude:
        - php: 7
          env: SYMFONY_VERSION=4.0.* # requires PHP ^7.1.3
        - php: 7
          env: SYMFONY_VERSION=dev-master # requires PHP ^7.1.3
    allow_failures:
        - php: nightly
        - env: SYMFONY_VERSION=dev-master

notifications:
    email:
        - "gregurco.vlad@gmail.com"
